### ISSUE TITLE
Does not support nodecg 2.2.0 and beyond

### ISSUE THREAD

**Issue by drB-dotjpg** [inkfarer/ipl-overlay-controls#128]
```
2024-02-10 16:38:38 - info: [server] Starting NodeCG 2.2.0 (Running on Node.js v16.14.2)
2024-02-10 16:38:40 - warn: [extensions] Failed to mount ipl-overlay-controls extension:
 ENOENT: no such file or directory, scandir 'undefined/bundles', Error: ENOENT: no such file or directory, scandir 'undefined/bundles'
    at readdirSync (node:fs:1392:3)
    at Object../src/extension/helpers/bundleHelper.ts (webpack://ipl-overlay-controls/src/extension/helpers/bundleHelper.ts:33:25)
    at null.__webpack_require__ (webpack://ipl-overlay-controls/webpack/bootstrap:19:1)
    at Object../src/extension/versionChecker.ts (webpack://ipl-overlay-controls/src/extension/versionChecker.ts:32:24)
    at null.__webpack_require__ (webpack://ipl-overlay-controls/webpack/bootstrap:19:1)
    at null.__webpack_modules__../src/extension/index.ts.module.exports (webpack://ipl-overlay-controls/src/extension/index.ts:49:5)
    at ExtensionManager._loadExtension (C:\Users\Derek\Documents\ipl-overlays\nodecg\src\server\server\extensions.ts:140:22)
    at null.ExtensionManager (C:\Users\Derek\Documents\ipl-overlays\nodecg\src\server\server\extensions.ts:56:12)
    at NodeCGServer.<anonymous> (C:\Users\Derek\Documents\ipl-overlays\nodecg\src\server\server\index.ts:330:28)
    at Generator.next (<anonymous>)
2024-02-10 16:38:40 - info: [server] NodeCG running on http://localhost:9090
```

Nodecg CLI lets you upgrade with `nodecg setup -u` and downgrade with `nodecg setup 2.1.0 -u` with no issues.

**Comment by inkfarer** [comment]
fixed in [4.10.1](https://github.com/inkfarer/ipl-overlay-controls/releases/tag/4.10.1)
